# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp

  

  platform :ios, '9.0'
  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WeatherApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp-tvOS

  target 'WeatherApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
